### ISSUE TITLE
Add Github configuration to workflow

### ISSUE THREAD

**Issue by Zlopez** [Zlopez/jira_sync#54]
Currently only pagure is synced in the Github workflow.

We should add Github as well. For now I would say to add everything on fedora-infra namespace, but only issues with `cpe` label. We also need a map of users as we do on Pagure. I have something ready. It's converting pagure usernames to GitHub ones.
```
abompard = "abompard"
akash = "t0xic0der"
amedvede = "freadrix"
arrfab = "arrfab"
dherrera = "dherrerace"
dkirwan = "davidkirwan"
jantill = "james-antill"
jnsamyak = "jnsamyak"
jrichardson = "james02135"
kevin = "nirik"
lsegura = "LenkaSeg"
nils = "nphilipp"
pmoura = "phsmoura"
ppolakov = "ppolakov"
rlerch = "ryanlerch"
thrcka = "humaton"
zlopez = "zlopez"
```

**Comment by nphilipp** [comment]
> For now I would say to add everything on fedora-infra namespace, …

I want to check if we can query the GitHub API for repositories in this org, and simply(!) point jira_sync to that and get all repositories sync’ed. This would save us a lot of typing and configuration maintenance.
