### ISSUE TITLE
Implement synchronization of GitHub issue tickets

### ISSUE THREAD

**Issue by gridhead** [Zlopez/jira_sync#8]
Implement synchronization of GitHub issue tickets

**Comment by nphilipp** [comment]
Step 0: Refine the ticket 😉. I’ll look into the code to cook up some acceptance criteria.

Here’s my first shot:

- [ ] An abstraction layer exists which separates code specific to Pagure from that which is generically useful. 
- [ ] An implementation to sync GitHub issues using that abstraction layer exists. This syncs the following between GitHub and JIRA:
  - [ ] …
  - [ ] …

**Comment by Zlopez** [comment]
The code should need some refactoring, at least separating the pagure and github parts of code.

**Comment by nphilipp** [comment]
> The code should need some refactoring, at least separating the pagure and github parts of code.

Yeah, that’s what the first Acceptance Criteria item is about.
